Adding rmarkdown to suggests (#189)
I got error:
```
error: processing vignette 'goshawk.Rmd' failed with diagnostics:
The 'rmarkdown' package should be installed and declared as a dependency of the 'goshawk' package (e.g., in the 'Suggests' field of DESCRIPTION), because the latter contains vignette(s) built with the 'rmarkdown' package.
```

---------

Co-authored-by: 27856297+dependabot-preview[bot]@users.noreply.github.com <27856297+dependabot-preview[bot]@users.noreply.github.com>